lib/api-request/index.js

This fix somehow disappeared in a merge, added it again.

port and secure are also options we would like to pass

---

README.md

Also added these two new API endpoints to the README file.

README following the API

---

api/endpoints/_test/get.js
api/endpoints/_test/missing-parameter.js
api/endpoints/_test/post.js
api/endpoints/_test/put.js
api/endpoints/_test/request-error.js

The problem was, that:
```javascript
var a = function * () {}
// a.constructor.name === 'GeneratorFunction'
var b = a.bind(this)
// b.constructor.name === 'Function'
```

Fixing unran test cases

---

api/endpoints/administrator/index.js
api/endpoints/administrator/index.spec.js
lib/api-request/index.js
test-mocks.js
translations/collect.js
translations/middleware.js
translations/middleware.spec.js
translations/render-decorator.js

- Translation collection signature changed to support api options
- added translation id to support multiple translation files (not only 'um' :)). There is no default, this parameter is required
- administrators endpoint changes to reflect 'data' field in the body
- fix boolean value fallbacks when determine api options

Translation review

---

README.md
api/endpoints/email/index.js
api/endpoints/email/index.spec.js

needed in editor... please pull if possible

email personalization setter and getter endpoints

---

api/endpoints/email/index.js
api/endpoints/email/index.spec.js

Integrated email version api endpoints mainly for content editor.

feat(email versions): integrate suite api email version manager endpoints

---

README.md
api/endpoints/settings/index.js
api/endpoints/settings/index.spec.js
api/index.js
api/index.spec.js
config.js
lib/superadmin-checker/index.js
lib/superadmin-checker/index.spec.js
package.json

Added IP restrictions endpoint and api proxy port to config

IP Restrictions + api port

---

README.md
api/endpoints/_base/index.js
api/endpoints/_base/index.spec.js
api/endpoints/segment/index.js
api/endpoints/segment/index.spec.js

The segmentation API expects the query parameters without
the question mark

Add support for segmentation

---

README.md
api/endpoints/email/index.js
api/endpoints/email/index.spec.js

feat(email): add responses and getdeliverystatus

---

README.md
api/endpoints/email/index.js
api/endpoints/email/index.spec.js

I added CRUD methods for tracked links, needed in CE.

feat(link-tracking): methods for tracked links of an email

---

lib/password-generator/index.js
lib/password-generator/index.spec.js
package.json

BREAKING CHANGE: added special character for password requirement
BREAKING CHANGE: use ES6 features in password generator

feat(password-generator): replace external password generator

---

api/endpoints/administrator/index.js
api/endpoints/administrator/index.spec.js
lib/date-helper/index.js
lib/date-helper/index.spec.js
package.json

BREAKING CHANGE: date helper returns current date in Vienna time
BREAKING CHANGE: invitation does not disable admins

feat(date-helper): current date in Vienna time

---

README.md
api/endpoints/contact/index.js
api/endpoints/contact/index.spec.js

This should allow creating contacts through update endpoint

feat(contact): add support for create or update of contact

---

README.md
api/endpoints/email/index.js
api/endpoints/email/index.spec.js
api/endpoints/keyring/index.js

Hello @Valetudox, can you check this? Needed in CE to load programs a campaign is linked to.

Email programs

---

api/endpoints/keyring/index.js
api/endpoints/keyring/index.spec.js

BREAKING CHANGE: suite api url changed

feat(keyring): keyring api path changed

---

README.md
api/endpoints/contact/index.js
api/endpoints/contact/index.spec.js

This is necessary to be able to delete contacts through the SDK.

feat(api): add contact delete endpoint

---

README.md
api/endpoints/email/index.js
api/endpoints/email/index.spec.js

feat(email-responses): fetch response summary for an email

---

package.json

BREAKING CHANGE: drop support for node<6

feat(package): update dependencies

---

api/endpoints/administrator/index.admin-list.js
api/endpoints/administrator/index.admin-list.spec.js
api/endpoints/administrator/index.js
api/endpoints/administrator/index.spec.js

BREAKING CHANGE: administrator.getSuperadmin removed, administrator.getSuperadmins should be used instead

feat(administrator): remove administrator.getSuperadmin

---

package.json

We've upgraded a few dependencies those NSP was complaining about.

Security patch

---

README.md

I did not find only the documentation regarding ```deleteAdministrator```
Closes #144

chore(doc): fix doc links

---

.eslintrc
api/endpoints/_base/index.spec.js
api/endpoints/_test/get.js
api/endpoints/_test/missing-parameter.js
api/endpoints/_test/post.js
api/endpoints/_test/put.js
api/endpoints/_test/request-error.js
api/endpoints/administrator/index.admin-list.spec.js
api/endpoints/administrator/index.spec.js
api/endpoints/combinedsegment/index.spec.js
api/endpoints/condition/index.js
api/endpoints/externalevent/index.js
api/endpoints/externalevent/index.spec.js
api/endpoints/keyring/index.js
api/index.spec.js
authentication/request/koa.spec.js
authentication/url/index.spec.js
authentication/url/koa.spec.js
lib/api-request/index.spec.js
lib/date-helper/index.spec.js
lib/superadmin-checker/index.js
lib/superadmin-checker/index.spec.js
package-lock.json
package.json
test-setup.spec.js
translations/middleware.spec.js
translations/translator.spec.js

**tl;dr**: this PR includes a massive dependency upgrade due to security and other reasons.
**Core:**
- escher-auth, escher-suiteapi-js
- flat
- lodash
- moment-timezone
- node-cache
- sprintf-js
- audit-fitler
**Release:** 
- semantic-release
- pre-commit
**Lint:** 
- eslint, eslint-config-emarsys, eslint-plugin-no-only-tests, eslint-plugin-security
**Test:** 
- chai, chai-as-promised, chai-subset
- mocha, co-mocha
- nock
- sinon, sinon-chai

feat(packages): upgrade dependencies

---

.nsprc

Prototype Pollution: https://npmjs.com/advisories/782

fix(audit): fix Prototype Pollution

---

README.md
api/endpoints/segment/index.js
api/endpoints/segment/index.spec.js

Issue: [SUITEDEV-16976](https://emarsys.jira.com/browse/SUITEDEV-16976)
* [Y] Have you followed our guidelines?
* [Y] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [Y] Is it a _public_ API endpoint that you want to implement?
* [Y] Did you follow other API endpoint implementations?
* [Y] Did you cover it with test(s)?
* [Y] Did you documented it in the [read me](https://github.com/emartech/suite-js-sdk/blob/master/README.md)?
* [Y] Did you link the Emarsys Developer Hub?

feat(api): Adding segment run functions for single contact to Segment endpoint

---

README.md
api/endpoints/purchase/index.js
api/endpoints/purchase/index.spec.js

* [ Y] Have you followed our guidelines?
* [ Y] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ Y] Is it a _public_ API endpoint that you want to implement?
* [ Y] Did you follow other API endpoint implementations?
* [ Y] Did you cover it with test(s)?
* [Y ] Did you documented it in the [read me](https://github.com/emartech/suite-js-sdk/blob/master/README.md)?
* [ N] Did you link the Emarsys Developer Hub?

feat(api): Add purchases stats endpoint

---

.nsprc
README.md
api/endpoints/contact/index.js
api/endpoints/contact/index.spec.js
package-lock.json

Reverts emartech/suite-js-sdk#156
As of a request from @BlasiusVonSzerencsi

Revert "Feat/contact checkids"

---

.nsprc
README.md
api/endpoints/contact/index.js
api/endpoints/contact/index.spec.js
package-lock.json

feat(api): contact check IDs endpoint

---

.nsprc
config.js
package-lock.json
package.json

BREAKING CHANGE:  from now on timeout works with zero

fix(config): enable notimeout

---

.nsprc
README.md
api/endpoints/contact/index.js
api/endpoints/contact/index.spec.js

Co-Authored-By: iben12 <iben12@users.noreply.github.com>

feat(api): contact query field changes endpoint CDP-1077

---

README.md
api/endpoints/email/index.js
api/endpoints/email/index.spec.js

EME-86
Co-authored-by: Balint Mori<balint.mori@emarsys.com>

feat(email): new method to broadcast email campaign to virtal contact

---

mocha.opts
package-lock.json
package.json

update dependencies
SECURITY-4335

Security fix

---

.npmrc
.nsprc
package-lock.json
package.json

fix(dependencies): update lodash, eslint, node-cache

---

package-lock.json
package.json

fix: update escher-suiteapi-js version due to security issue

---

package-lock.json
package.json

fix: updates deps due to security issues 

---

package-lock.json
package.json

fix: updates deps due to security issues

---

translations/render-decorator.js

Co-authored-by: David Szigecsan <david.szigecsan@emarsys.com>
recent changes in koa-pug rendering (async/await model instead of the plain function) requires the added return statement

fix: add return statement to renderWithTranslations

---

package-lock.json
package.json
translations/collect.js

Replaced co-request with axios. Additionally made updates on dev dependencies that contained additional vulnerabilities. The remaining vulnerabilities on semantic-release could not be updated.
Relates [SUITEDEV-29314](https://emarsys.jira.com/browse/SUITEDEV-29314)

fix: fixing a critical co-request vulnerability

---

package-lock.json
package.json

* [✓] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

At 3835 - update axios and moment-timezone

---

package-lock.json
package.json

Co-Authored-By: BlasiusVonSzerencsi <BlasiusVonSzerencsi@users.noreply.github.com>

chore(package): update npm audit findings CDP-1737

---

README.md
api/endpoints/_test/delete.js
api/endpoints/_test/index.js
api/endpoints/field/index.js
api/endpoints/field/index.spec.js
lib/api-request/index.js
lib/api-request/index.spec.js

feat(field): add contact field DELETE CDP-1737

---

package-lock.json
package.json

* [-] Is it a _public_ API endpoint that you want to implement?
* [-] Did you follow other API endpoint implementations?
* [-] Did you cover it with test(s)?
* [-] Did you documented it in the [read me](https://github.com/emartech/suite-js-sdk/blob/master/README.md)?
* [-] Did you link the Emarsys Developer Hub?

fix(package): update moment-timezone

---

package-lock.json
package.json

BREAKING CHANGE: See v21.0.0 of @emartech/escher-request

chore(package): update @emartech/escher-request

---

api/endpoints/_base/index.js
api/endpoints/contactlist/index.js
api/endpoints/contactlist/index.spec.js

fix: build url without slash for new fetch contact list

---

package-lock.json
package.json

* [ x] Have you followed our guidelines?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

fix(EME-OPS): bump axios version

---

package-lock.json
package.json

Co-authored-by: Dominik Nyerges <dominik.nyerges@emarsys.com>

fix(EM-6472): bump escher-request version

---

package-lock.json
package.json

fix(axios): Update to version 1.7.5.

---

package-lock.json
package.json

fix(axios): upgrade @emartech/escher-request to 21.1.1

---

authentication/url/koa.js
authentication/url/koa.spec.js

fix(url_authentication): proper validated data for HEAD requests

---

package-lock.json
package.json

chore: update axios to 1.7.9

---

package-lock.json
package.json

fix(axios): upgrade @emartech/escher-request to 21.1.2

---

translations/collect.js
translations/middleware.spec.js

fix(translations): collect translations through HTTPS

---

package-lock.json
package.json

fix(axios): EME-12035 - upgrade @emartech/escher-request to 21.1.6
